services:
  xui:
    image: enwaiax/x-ui:alpha-zh
    container_name: alphazh
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    restart: unless-stopped
    network_mode: host
